### ISSUE TITLE
New installation instructions

### ISSUE THREAD

**Issue by erikthorselius** [homeki/homekicore#11]
The repository seems to changed to https (nice!) but on at least raspbian I need to install apt-transport-https. Don't know if the package apt-transport-https is specific instruction to raspbian or not. And the adress on the wiki need to be updated to https://repository.homeki.com.

I also get https errors "W: Failed to fetch https://repository.homeki.com/packages/dists/stable/main/binary-armhf/Packages  SSL: certificate subject name (*.s3-eu-west-1.amazonaws.com) does not match target host name 'repository.homeki.com'"

**Comment by erikthorselius** [comment]
My bad, found out that the stable branch is gone. Guess the only change in the instruction is to only go with unstable or upload some stable packages.

**Comment by joscarsson** [comment]
Debian repository now moved to S3 using https://github.com/krobertson/deb-s3, `stable` exists again. Unfortunately no https yet :)
